#ifndef CONFIG_H
#define CONFIG_H

#include <cmath>

#ifndef CONFIG_DYNAMIC
#define CONFIG_DYNAMIC

#define OBSTACLE_OFFSET 100.
#define OBSTACLE_FIELD_REDUCTION .6
#define ASTAR_HEURISTIC_COEFFICIENT 1.

#endif  // CONFIG_DYNAMIC

#ifndef CONFIG_BOT
#define CONFIG_BOT
#define CONFIG_BETABOT
#endif  // CONFIG_BOT

#ifndef CONFIG_BETABOT
#define CONFIG_BETABOT
#endif  // CONFIG_BETABOT

#ifndef CONFIG_ALPHABOT
#define CONFIG_ALPHABOT

#define ARM_MAX_RPS (2 * M_PI)
#define ELEVATOR_MAX_RPS (2 * M_PI)
#define ARM_MAX_RPSS 0.01
#define ELEVATOR_MAX_RPSS 0.01

#define ROBOT_WIDTH 0.7
#define ROBOT_HEIGHT 0.2
#define ROBOT_2_L1_FRONT 0.05

#define ELEVATOR_2_L1_FRONT 0.4
#define ELEVATOR_2_GROUND 0.2
#define ELEVATOR_2_GROUND_ANGLE 80.0
#define ELEVATOR_SIN_ANGLE sin(ELEVATOR_2_GROUND_ANGLE / 180 * M_PI)
#define ELEVATOR_COS_ANGLE cos(ELEVATOR_2_GROUND_ANGLE / 180 * M_PI)

#define ELEVATOR_MIN_POSITION 0
#define ELEVATOR_MAX_POSITION 2.0
#define ELEVATOR_GRID_SIZE 0.05
#define ELEVATOR_GRID_NUMS (floor((ELEVATOR_MAX_POSITION - ELEVATOR_MIN_POSITION) / ELEVATOR_GRID_SIZE) + 1)
#define ELEVATOR_REDUCTION 1.0
#define ELEVATOR_ROTATION_2_POSITION (1.0 / 2 / M_PI)
#define ELEVATOR_VMAX (ELEVATOR_MAX_RPS / ELEVATOR_REDUCTION * ELEVATOR_ROTATION_2_POSITION)
#define ELEVATOR_AMAX (ELEVATOR_MAX_RPSS / ELEVATOR_REDUCTION * ELEVATOR_ROTATION_2_POSITION)

#define ARM_MIN_THETA_ROTATION 0
#define ARM_MAX_THETA_ROTATION 350
#define ARM_MIN_THETA_RADIAN (ARM_MIN_THETA_ROTATION / 180 * M_PI)
#define ARM_MAX_THETA_RADIAN (ARM_MAX_THETA_ROTATION / 180 * M_PI)
#define ARM_GRID_SIZE 0.1
#define ARM_GRID_NUMS (floor((ARM_MAX_THETA_RADIAN - ARM_MIN_THETA_RADIAN) / ARM_GRID_SIZE) + 1)
#define ARM_REDUCTION 1.0
#define ARM_VMAX (ARM_MAX_RPS / ARM_REDUCTION)
#define ARM_AMAX (ARM_MAX_RPSS / ARM_REDUCTION)

#define ARM_MAX_VOLTAGE 12
#define ARM_Kv 1
#define ARM_Ka 1
#define ELEVATOR_MAX_VOLTAGE 12
#define ELEVATOR_Kv 1
#define ELEVATOR_Ka 1

#endif  // CONFIG_ALPHABOT

#ifndef CONFIG_ENV
#define CONFIG_ENV

#define L1_FRONT_HEIGHT 0.454
#define L1_BACK_HEIGHT 0.514
#define L1_FRONT_2_L1_BACK 0.248
#define L1_BACK_2_REEF_CENTER (0.832 - L1_FRONT_2_L1_BACK)
#define REEF_CENTER_HEIGHT 1.2

#define BRANCH_DIAMETER 0.042
#define BRANCH_UL_X 0.296
#define BRANCH_UL_Y 1.35
#define BRANCH_UR_X (BRANCH_UL_X + BRANCH_DIAMETER)
#define BRANCH_UR_Y BRANCH_UL_Y
#define BRANCH_LR_X BRANCH_UR_X
#define BRANCH_LR_Y 0.0
#define BRANCH_LL_X BRANCH_UL_X
#define BRANCH_LL_Y BRANCH_LR_Y

#define L4_UL_X 0.030
#define L4_UL_Y 1.810
#define L4_UR_X (L4_UL_X + BRANCH_DIAMETER)
#define L4_UR_Y L4_UL_Y
#define L4_LR_X L4_UR_X
#define L4_LR_Y (L4_UR_Y - 0.173)
#define L4_LL_X L4_UL_X
#define L4_LL_Y L4_LR_Y

#define L3_UL_X 0.053
#define L3_UL_Y 1.194
#define L3_LL_X 0.029
#define L3_LL_Y 1.16
#define L3_UR_X BRANCH_LL_X
#define L3_UR_Y 1.024
#define L3_LR_X BRANCH_LL_X
#define L3_LR_Y 0.973

#define L2_UL_X L3_UL_X
#define L2_UL_Y 0.79
#define L2_LL_X L3_LL_X
#define L2_LL_Y (L2_UL_Y - (L3_UL_Y - L3_LL_Y))
#define L2_UR_X L3_UR_X
#define L2_UR_Y (L2_UL_Y - (L3_UL_Y - L3_UR_Y))
#define L2_LR_X L3_LR_X
#define L2_LR_Y (L2_LL_Y - (L3_LL_Y - L3_LR_Y))

#define ALGAE_HIGH_CENTER_X 0.7
#define ALGAE_HIGH_CENTER_Y 1.2
#define ALGAE_LOW_CENTER_X ALGAE_HIGH_CENTER_X
#define ALGAE_LOW_CENTER_Y 0.4
#define ALGAE_RADIUS 0.41

#endif  // CONFIG_ENV

#endif  // CONFIG_H
